// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Reads the access token directly from localStorage instead of calling
// supabase.auth.getSession() — getSession() is expensive because it may
// trigger a network round-trip to refresh the token. The Supabase client
// already handles refresh automatically via onAuthStateChange, so the
// token in storage is always up-to-date.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let token = "";
    if (typeof window !== "undefined") {
      try {
        const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
        const storageKey = `sb-${new URL(SUPABASE_URL).hostname.split(".")[0]}-auth-token`;
        const raw = localStorage.getItem(storageKey);
        if (raw) {
          const parsed = JSON.parse(raw);
          token = parsed?.access_token ?? "";
        }
      } catch {
        // ignore parse errors
      }
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
