// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" })
  .client(async ({ next }) => {
    // Read the Supabase session token from client
    let token = "";
    if (typeof window !== "undefined") {
      try {
        const { supabase } = await import("./client");
        const { data } = await supabase.auth.getSession();
        token = data.session?.access_token ?? "";

        // Fallback: search localStorage keys
        if (!token) {
          for (let i = 0; i < localStorage.length; i++) {
            const k = localStorage.key(i);
            if (k && k.startsWith("sb-") && k.endsWith("-auth-token")) {
              const raw = localStorage.getItem(k);
              if (raw) {
                const parsed = JSON.parse(raw);
                token = parsed?.access_token ?? "";
                if (token) break;
              }
            }
          }
        }
      } catch {
        // ignore parse errors
      }
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  })
  .server(async ({ next }) => {
    const SUPABASE_URL =
      process.env.SUPABASE_URL ||
      import.meta.env.VITE_SUPABASE_URL ||
      "https://mbvjnqaufjykgpjkudju.supabase.co";
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idmpucWF1Zmp5a2dwamt1ZGp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2ODEyNjgsImV4cCI6MjEwMzI1NzI2OH0.DoGk9MP_bgMg0ewqy3ftJFRc67wUwE0EFmukMbi8HKo";

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      console.error("[Supabase Auth] No authorization header found in request");
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      console.error("[Supabase Auth] Token validation failed:", error?.message ?? "no claims");
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  });
